### ISSUE TITLE
Wrong path in MSFT_xSCSMARunbookWorkerServerSetup.psm1

### ISSUE THREAD

**Issue by mortenlerudjordet** [PowerShell/xSCSMA#15]
On line 56 & 176:
$Path = Join-Path -Path (Join-Path -Path $SourcePath -ChildPath $SourceFolder) -ChildPath **"\SMA\WebServiceSetup.exe"**

As this is the setup for RunbookWorker I asume this should be:
**"\SMA\WorkerSetup.exe"**

**Comment by dcrreynolds** [comment]
I'll take care of this and the other related issue together.

**Comment by johlju** [comment]
This should have been resolved in PR #17.
