### ISSUE TITLE
Unknown version numbers?!

### ISSUE THREAD

**Issue by bk147** [PowerShell/xSCSMA#18]
I'm a bit mystified by your version numbers in MSFT_xSCSMAPowerShellSetup.
When I download System Center 2016 Orchestrator from MVLS, the version I get for SetupOrchestrator.exe is 7.3.149.0?!? (the other resources are correct - e.g. 7.3.345.0)

Best,
-Brian

**Comment by johlju** [comment]
This was resolved in PR #21.
