### ISSUE TITLE
xSCSMAWebServiceServerSetup: always install self-signed certificate

### ISSUE THREAD

**Issue by pvs043** [PowerShell/xSCSMA#19]
1.  'SpecifyCertificate' parameter isn't transferred when installing WebServiceInstaller.msi. Default is 'No'.
2. Using 'CertificateSerialNumber' instead of 'CertificateSerial'.
3. Hard-coded 'UseSSL=Yes' when install MSI.

[Install Service Management Automation from a Command Prompt window](https://technet.microsoft.com/en-us/system-center-docs/sma/deploy/install-service-management-automation-from-a-command-prompt-window)

**Comment by johlju** [comment]
This was resolved in PR #21.
