### ISSUE TITLE
System Center 2016 use SendTelemetryReports instead SendCEIPReports

### ISSUE THREAD

**Issue by pvs043** [PowerShell/xSCSMA#20]
When installing WebServiceInstaller.msi and WorkerInstaller.msi, use 'SendCEIPReports' parameter with System Center 2012 R2 and 'SendTelemetryReports' parameter with System Center 2016.

[System Center 2016 command line parameters](https://technet.microsoft.com/en-us/system-center-docs/sma/deploy/install-service-management-automation-from-a-command-prompt-window)

**Comment by johlju** [comment]
This was resolved in PR #21.
