### ISSUE TITLE
Examples for installing SMA using SC2016

### ISSUE THREAD

**Issue by ricardogaspar2** [PowerShell/xSCSMA#22]
Hey,
Can you post some examples of DSC configuration scripts for installing SMA using System Center Orchestrator 2016?

**Comment by johlju** [comment]
Can you describe the scenario a bit more, what you try to accomplish? What is the reasoning for wanting to do this with System Center Orchestrator 2016?

**Comment by bgelens** [comment]
@johlju SMA is packaged on the orchestrator media

**Comment by ricardogaspar2** [comment]
I'm not working on this anymore. I wanted to install only SMA using the software package of SC Orchestrator 2016. This was a long time ago, and as I didn't get any answers at the time I put this on the side.

**Comment by johlju** [comment]
@bgelens Aha, I see! 

@ricardogaspar2 There are examples here; https://github.com/PowerShell/xSCSMA/blob/dev/Examples. Although not sure if they are tested with SMA that comes with SCO2016. There are also more resources here that should be moved here (issue #13); https://github.com/robwi/xSCSMA/tree/master/DSCResources
