### ISSUE TITLE
BLOCKER: PSSA Errors Need to Be Fixed

### ISSUE THREAD

**Issue by kwirkykat** [PowerShell/xSCSMA#7]
Errors from PS script analyzer are causing the tests to fail like [this](https://ci.appveyor.com/project/PowerShell/xscsma/build/1.3.39.0).
This resource module cannot be released until these errors are fixed or suppressed and the tests are passing.

**Comment by Stijnc** [comment]
@kwirkykat as these are only samples, could a workaround like below provide a solution as it tricks the default scriptanalyzer rules?

``` PowerShell
$Username = 'MyUser'
$MyPlainTextPassword = 'P@ssw0rd!'
$Password = New-Object -Type SecureString 
[char[]] $MyPlainTextPassword | foreach-object {$Password.AppendChar( $_ ) }
$Credential = New-Object System.Management.Automation.PSCredential ($Username, $Password)
```

**Comment by kwirkykat** [comment]
@Stijnc We allow PSSA rule suppression for examples and tests, so you don't have to change the sample unless it's needed.
You can put this attribute above the param block of any test files, example files, or functions with the appropriate names of PSSA rules you would like to suppress:

``` powershell
[Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSAvoidUsingConvertToSecureStringWithPlainText", "")]
param ()
```
